id: boid-kits
name: boid-kits

task_behaviors:
  dev:
    name: development
    transition: one-shot
    traits: [ instructions ]
    default_payload:
      instructions:
        main:
          type: execution
          consumer: claude-code
          message: "タスクを実装してください。完了したらコミットしてください."


kits:
  - github.com/novshi-tech/boid-kits/git
  - github.com/novshi-tech/boid-kits/claude-code
  - github.com/novshi-tech/boid-kits/codex
